apiVersion: batch/v1
kind: Job
metadata:
  name: seed
  namespace: hotrod
spec:
  template:
    spec:
      containers:
      - name: seed
        image: registry.hub.docker.com/hantaowang/hotrod-seed
        command: ["make",  "seed"]
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: customer-configs
              key: postgres-user
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgres-password
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password        
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: customer-configs
              key: postgres-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: driver-configs
              key: redis-url
      restartPolicy: Never
  backoffLimit: 4
